version: '3'
services:
  nginx:
    container_name: 'nginx'
    image: nginx:lts
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/nginx/conf:/etc/nginx
      - /data/frontend/build:/var/www/html
      - /data/ssl:/etc/letsencrypt
    networks:
      - service1
  spring:
    container_name: 'backend'
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - service1
  frontend:
    container_name: 'frontend'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - service1
    volumes :
      - /data/frontend/build:/app/frontend/dist
  redis:
    image: redis
    ports:
      - 6379:6379
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
  openvidu:
    image: openvidu/openvidu-dev:2.29.0
    ports:
      - 4443:4443
    environment:
      OPENVIDU_SECRET: '${MY_SECRET}'
networks:
  service1:
