version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
  openvidu:
    image: openvidu/openvidu-dev:2.29.0
    ports:
      - 4443:4443
    environment:
      OPENVIDU_SECRET: '${MY_SECRET}'

