pipeline {
    agent any
    environment {
        BACKEND = 'backend'
        TAG = 'latest'
        RENAME_JAR = 'backend'
        BUILD_CMD = 'bootJar'
        WORKSPACE_DIR = ''
    }
    stages {        
       

        stage('build spring project') {
            steps {
                sh 'ls -al'
            
            }
        }

    }
}

