spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/tutorcall?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
